[package]
name = "search-for-the-chief-historian"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.6"
eyre = "0.6.12"
thiserror = "2.0.5"
ureq = { version = "2.12.1", features = ["cookies"] }
